### ISSUE TITLE
Do you accept Hate Speach?

### ISSUE THREAD

**Issue by GrandmasterPennell** [jstayton/suri#18]
i am highly offended. 
![image](https://user-images.githubusercontent.com/89934308/147430716-46c87fe4-36d4-4b96-aed5-78037ade99f3.png)

**Comment by GrandmasterPennell** [comment]
Your moderators put people down because they have a handicap.

**Comment by kaovilai** [comment]
I don't think this suri is related to the game studios.

**Comment by GrandmasterPennell** [comment]
its the same 1. https://www.youtube.com/watch?v=gypm7x9bSD0

**Comment by kaovilai** [comment]
> Suri is your own link shortener that's easily deployed as a static site. No server-side hosting, serverless cloud functions, or database necessary. Suri can be deployed to Vercel, Netlify, and more for free in 60 seconds.

https://github.com/jstayton/suri

**Comment by jstayton** [comment]
Yeah, I have no idea what this is about, but it's certainly not related to this open source link shortener. Sorry, but I can't help.
