### ISSUE TITLE
Feature request: support YAML for links.json

### ISSUE THREAD

**Issue by tyteen4a03** [jstayton/suri#30]
I would like an option to add comments to my links, which JSON doesn't allow.

**Comment by jstayton** [comment]
Hey Timothy – Sorry for the delay in responding. I can understand how comments could be handy, but supporting YAML would require pulling in an additional dependency and making it work with Eleventy, which doesn't support YAML for data files. For now I'm going to say that this probably won't happen. I'll keep it in mind though.

Thanks for your feedback!
